
title: Test
email: exampe@example.com
description: >- # this means to ignore newlines until "baseurl:"
  TPI team dev docs site
baseurl: "/pages_test" # the subpath of your site, e.g. /blog

theme: just-the-docs
# remote_theme: pmarsceill/just-the-docs

exclude:
  - Gemfile
