
title: Test
email: exampe@example.com
description: >- # this means to ignore newlines until "baseurl:"
  TPI team dev docs site
baseurl: "" # the subpath of your site, e.g. /blog

markdown: kramdown

theme: just-the-docs
# remote_theme: pmarsceill/just-the-docs

# exclude:
#   - Gemfile
