version: "3"
services:
  site:
    container_name: pages_test
    command: jekyll serve --force_polling --config _config_local.yml
    image: jekyll/jekyll:latest
    environment:
      JEKYLL_DEV: dev
    volumes:
      - .:/srv/jekyll
    ports:
      - 4001:4000
  # build:
  #   container_name: mtpi-dev-docs-build
  #   command: jekyll build
  #   image: jekyll/jekyll:latest
  #   volumes:
  #     - .:/srv/jekyll
